/**
 * City Configuration from Excel Location Value Sheets & Real Property Valuation Manual
 * Extracts cities and their reference data from the property valuation excel files and manual
 */

// Addis Ababa Sub-Cities/Zones from Real Property Valuation Manual (Condominium sites)
// Per ZamZam Bank Real Property Valuation Manual May 2023
export const ADDIS_ABABA_SUBCITIES = [
  "Addis Ketema",
  "Gulele",
  "Ajamba",
  "Amanuel",
  "Atikilt Tera",
  "Aware",
  "Ayat - Tafo",
  "Ayat - 1",
  "Ayat - 2",
  "Ayat - 3",
  "Ayat - 4",
  "Balderas",
  "Basha Wolde",
  "Bole Arabsa",
  "Bole Bulbula",
  "Cherkos",
  "Deginet",
  "Feres Bet",
  "Gelan",
  "Gerjie",
  "Gofa Camp",
  "Gotera",
  "Haile Garment",
  "Jemo -1",
  "Jemo -2",
  "Jemo -3",
  "Kality Total",
  "Klinto",
  "Koye Feche",
  "Laphto - 1",
  "Laphto - 2",
  "Lideta",
  "Mekanissa",
  "Menen",
  "Meskel Flower",
  "Mikili Land",
  "Repi1 (Girar)",
  "Repi - 2",
  "Saris",
  "Summit",
  "Teklehaimanot",
  "Torhalloch",
  "Tsion",
  "Tulu Dimtu",
  "Woira",
  "Yeka Abado",
  "Yigezu (Enkulal Fabrika)",
  "Enderasie",
  "Yeka Adwa",
];

// All cities available in the property valuation system
// Source: Location Value Sheets from XY-1 and sample-report Excel files
export const CITIES = [
  "Adama",
  "Addis Ababa",
  "Addis Zemen",
  "Adi Shehu",
  "Adigrat",
  "Adigudem",
  "Agaro",
  "Agula'e",
  "Ahse'a",
  "Aleta Wondo",
  "Amba Giyorgis",
  "Ambo",
  "Anger Gute",
  "Arba Minch",
  "Arbaya",
  "Asayta",
  "Assela",
  "Assosa",
  "Atsbi",
  "Awash Melkassa",
  "Axum",
  "Ayra",
  "Bahirdar",
  "Bako",
  "Bale Goba",
  "Bale Robe",
  "Bati",
  "Begi",
  "Bekoji",
  "Bila",
  "Bishoftu",
  "Bizet",
  "Bonga",
  "Bule Hora",
  "Burayu",
  "Burayu (Anfo)",
  "Butajira",
  "Chagni",
  "Chiro",
  "Daye (Bensa)",
  "Debre Birhan",
  "Debre Markos",
  "Debre Tabor",
  "Dejen",
  "Dembecha",
  "Dembi Dollo",
  "Dera",
  "Desse",
  "Dilla",
  "Diredawa",
  "Dukem",
  "Durame",
  "Ebinat",
  "Edaga Hamus",
  "Enticho",
  "Eteya",
  "Fatsi",
  "Feresmay",
  "Fincha",
  "Finote selam",
  "Fireweini",
  "Fitche",
  "Gambela",
  "Gedo",
  "Gelan",
  "Genda Wuha",
  "Genet Adebabay",
  "Ghimbi",
  "Gida",
  "Gidami",
  "Gijet",
  "Gilgelbeles",
  "Gondor",
  "Gore",
  "Guduru",
  "Guhala",
  "Guliso",
  "Harar",
  "Hawassa",
  "Hawzen",
  "Hiwane",
  "Holeta",
  "Hossana",
  "Humera",
  "Jijiga",
  "Jimma",
  "Kimir Dingay",
  "Korem",
  "LEKU",
  "LIMMU",
  "Legetafo",
  "MAICHEW",
  "MAIKNETAL",
  "MAKSEGNIT",
  "MARAYA",
  "MASHA",
  "MEKI",
  "MEKONI",
  "MENDI",
  "METEHARA",
  "MODJO",
  "Mekele",
  "Mettu",
  "Mizan",
  "Moyale",
  "NAEDER ADET",
  "NEDJO",
  "NEGELLE BORENA",
  "NEKEMTE",
  "SAMRE",
  "SANJA",
  "SEBETA/ALEMGENA",
  "SEBETA/ALEMGENA(FURI)",
  "SELEKLEKA",
  "SENDAFA",
  "SHAMBU",
  "SHERARO",
  "SHIRE ENDASILASSIE",
  "SIMADA",
  "SOROKA",
  "SULULTA",
  "Shashemene",
  "TULU BOLO",
  "Tepi",
  "WELENCHITI",
  "WERIELEKE",
  "WERKAMBA",
  "WOLDIA",
  "WOLISO",
  "WOLLAYTA SODO",
  "WUQRO",
  "Wolkite",
  "YECHILA",
  "YIRGA CHEFE",
  "YIRGALEM",
  "ZWAY",
  "kombolcha",
  "kombolcha New"
].sort();

// Location value lookup table - stores default rates for cities
// Source: Location Value Sheets in Excel
export const LOCATION_RATES: Record<string, number> = {
  "Addis Ababa": 26368,
  "Adama": 10312,
  "Bahirdar": 8500,
  "Diredawa": 7200,
  "Hawassa": 6800,
  "Jimma": 5200,
  "Mekele": 4800,
  "Bishoftu": 3400,
  "Dukem": 2800,
  "Debre Markos": 3200,
  "Assela": 2100,
  "Holeta": 2200,
  "Debre Birhan": 2400,
  "Modjo": 2600,
  "Sululta": 1800,
  "Gondor": 3600,
  "Arba Minch": 3000,
  "Axum": 2000,
  "Harar": 5000,
  "Dire Dawa": 7200,
  "Gambela": 1500,
  "Jijiga": 2720,
  "Wolkite": 1600,
};

// Get the default location rate for a city
export function getDefaultLocationRate(city: string): number {
  const normalized = city.toLowerCase().trim();
  
  // Try exact match
  for (const [key, rate] of Object.entries(LOCATION_RATES)) {
    if (key.toLowerCase() === normalized) {
      return rate;
    }
  }
  
  // Fallback to a reasonable default (Addis Ababa rate)
  return 26368;
}

// Get sub-cities for a given city
export function getSubCities(city: string): string[] {
  if (city === "Addis Ababa") {
    return ADDIS_ABABA_SUBCITIES;
  }
  return [];
}

// City categories for grouping in UI
export const CITY_CATEGORIES = {
  "Major Cities": ["Addis Ababa", "Adama", "Bahirdar", "Diredawa", "Hawassa", "Jimma", "Mekele"],
  "Regional Cities": ["Bishoftu", "Dukem", "Debre Markos", "Assela", "Holeta", "Debre Birhan", "Modjo", "Gondor", "Arba Minch", "Axum", "Harar", "Wolkite"],
  "Other Cities": CITIES.filter(city => !["Major Cities", "Regional Cities"].flat().includes(city))
};
